global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Future API
  - job_name: "api"
    static_configs:
      - targets: ["api:8080"]
